### ISSUE TITLE
Removing raw Go invocation in librclone-sys build.rs

### ISSUE THREAD

**Issue by brettalcox** [trevyn/librclone#12]
Hi there! 

I'm currently trying to get an Gentoo ebuild written for Celeste, and I'm running into a bit of trouble with this crate and its raw usage of Go in the build.rs. Would it be possible to generate the bindings using something like pkg_config?

**Comment by trevyn** [comment]
As you note, access to a recent `go` compiler binary in the path at build time is assumed. Could you be a bit more specific about what you’re proposing or the problem you’re running into?

**Comment by brettalcox** [comment]
@trevyn I'm not super well versed in Go so forgive my ignorance :grin: I'm writing a "cargo"-based ebuild, which is pulling all of the necessary crates to use during the build phase. My specific problem with this crate is that its calling out to the network when at this point, the process is already network sandboxed. Since this crate is "dynamic" in that it generates the bindings each time it's used, I think the only way for me to work around this would be to generate the bindings myself and put into a new crate?

**Comment by trevyn** [comment]
So this crate isn't really just generating bindings, it's also compiling and statically linking in `rclone`, which is a full Go application. While the Go dependencies are locked and exactly specified by hashes, by default it does rely on the network to fetch the actual dependency code.

So it sounds like the actual issue is that you're building in a network-sandboxed environment? It should be possible to vendor the Go dependencies beforehand so that no network is necessary, but that'll definitely require some research and experimentation. I'm not familiar with how ebuild works; are you vendoring everything beforehand somewhere, or splitting the build phases into network-allowed and networked-sandboxed phases? Do you have a work-in-progress repo I could look at?

**Comment by brettalcox** [comment]
@trevyn yeah that's essentially what I'm doing. ebuild has several "helper" classes you can inherit from, a cargo build helper being one of them. It essentially pulls all crates into a local repo, does a `replace-with` (local-repo) on the crates-io, therefore you've got everything at build time. I can try playing around with vendoring the Go deps and see how that works

**Comment by trevyn** [comment]
So it looks like Go has pretty good vendoring support with `go mod vendor`; this could be run in the publish CI action so that the published crate has the vendor directory included but we wouldn't have to clutter this repo with it. It'll make the `-sys` crate about an 11.5MB download, but that's all deps that would have to be downloaded anyway. crates.io seems to have a 10MB default limit, but that appears to be override-able upon request. I'll sleep on it and then maybe push a test update tomorrow.

**Comment by trevyn** [comment]
Ok, published `librclone` 0.6.1 and `librclone-sys` 0.6.1, which should include fully vendored Go code, and work in an offline build. Please let me know if this works or doesn't work for you! :)

**Comment by brettalcox** [comment]
Thank you so much! I'll give this a shot later

**Comment by brettalcox** [comment]
@trevyn I think this gets me moving in the right direction. I'm running into some issues still but it's mainly around paths and the environment that it's operating in. The vendored deps work as expected though so thank you!

**Comment by trevyn** [comment]
Glad to hear the vendored bit is working! Feel free to reopen or open another issue if there’s anything I can help with.
